[project]
name = "hr-analytics-demission"
version = "0.1.0"
description = "Analyse des causes de démission des employés de TechNova Partners"
readme = "README.md"
requires-python = ">=3.10,<3.13"
authors = [
    { name = "Nicolas", email = "nicolas@example.com" }
]

dependencies = [
    "pandas>=2.0",
    "numpy>=1.24",
    "matplotlib>=3.7",
    "seaborn>=0.12",
    "scikit-learn>=1.3",
    "jupyter>=1.0",
    "notebook>=7.0",
    "shap>=0.44",
]

[tool.uv]
